2021-10-02 21:07:13,689:DEBUG:certbot._internal.main:certbot version: 1.19.0
2021-10-02 21:07:13,689:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2021-10-02 21:07:13,689:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/usr/share/nginx/html/letsencrypt', '--email', 'thuseynovint@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'playsdev.ddns.net']
2021-10-02 21:07:13,690:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-10-02 21:07:13,704:DEBUG:certbot._internal.log:Root logging level set at 30
2021-10-02 21:07:13,705:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2021-10-02 21:07:13,710:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: Authenticator, Plugin
Entry point: webroot = certbot._internal.plugins.webroot:Authenticator
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7faefbfaf700>
Prep: True
2021-10-02 21:07:13,710:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7faefbfaf700> and installer None
2021-10-02 21:07:13,710:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2021-10-02 21:07:13,717:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/223689500', new_authzr_uri=None, terms_of_service=None), dba54028421adec57f6139d6c00745e9, Meta(creation_dt=datetime.datetime(2021, 10, 2, 16, 44, 55, tzinfo=<UTC>), creation_host='0628ce4bab42', register_to_eff=None))>
2021-10-02 21:07:13,718:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2021-10-02 21:07:13,720:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2021-10-02 21:07:14,287:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2021-10-02 21:07:14,287:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 02 Oct 2021 21:07:14 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "NWcT4HxJQac": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2021-10-02 21:07:14,310:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer <certbot._internal.cli.cli_utils._Default object at 0x7faefbf41df0>
2021-10-02 21:07:14,319:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): r3.o.lencr.org:80
2021-10-02 21:07:14,324:DEBUG:urllib3.connectionpool:http://r3.o.lencr.org:80 "POST / HTTP/1.1" 200 503
2021-10-02 21:07:14,325:DEBUG:certbot.ocsp:OCSP response for certificate /etc/letsencrypt/archive/playsdev.ddns.net/cert1.pem is signed by the certificate's issuer.
2021-10-02 21:07:14,327:DEBUG:certbot.ocsp:OCSP certificate status for /etc/letsencrypt/archive/playsdev.ddns.net/cert1.pem is: OCSPCertStatus.GOOD
2021-10-02 21:07:14,330:DEBUG:certbot._internal.display.obj:Notifying user: Certificate not yet due for renewal
2021-10-02 21:07:14,332:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1572, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1425, in certonly
    should_get_cert, lineage = _find_cert(config, domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 325, in _find_cert
    action, lineage = _find_lineage_for_domains_and_certname(config, domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 356, in _find_lineage_for_domains_and_certname
    return _find_lineage_for_domains(config, domains)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 301, in _find_lineage_for_domains
    return _handle_identical_cert_request(config, ident_names_cert)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 253, in _handle_identical_cert_request
    response = display_util.menu(question, choices,
  File "/opt/certbot/src/certbot/certbot/display/util.py", line 104, in menu
    return obj.get_display().menu(message, choices, default=default, cli_flag=cli_flag,
  File "/opt/certbot/src/certbot/certbot/_internal/display/obj.py", line 121, in menu
    code, selection = self._get_valid_int_ans(len(choices))
  File "/opt/certbot/src/certbot/certbot/_internal/display/obj.py", line 378, in _get_valid_int_ans
    ans = util.input_with_timeout(input_msg)
  File "/opt/certbot/src/certbot/certbot/_internal/display/util.py", line 66, in input_with_timeout
    raise EOFError
EOFError
2021-10-02 21:07:14,333:ERROR:certbot._internal.log:An unexpected error occurred:
2021-10-02 21:07:14,334:ERROR:certbot._internal.log:EOFError
